package interfacez;

import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import laboratorio_clinico.conexion_MYSQL;

public class Home extends javax.swing.JFrame {

    // Esrtablecer conexion a MYSQL
    conexion_MYSQL c = new conexion_MYSQL();
    Connection conectar = c.obtener_conexion();

    DefaultTableModel model;

    String[] Campos_tabla = {"# Cita", "Paciente", "Medico", "Especialidad", "Modalidad", "Fecha Cita", "Hora Cita", "Sede"};
    String[] informacion = new String[50];

    public void mostrar_citashoy() {
        
        String Query = "SELECT c.ID_Cita, p.Nombres AS NombrePaciente, m.Nombre AS NombreMedico, em.NombreEspecialidad AS Especialidad, mc.NombreModalidad AS ModalidadConsulta, c.FechaCita, c.HoraCita, s.NombreSede AS Sede FROM citas c "
                     + "JOIN pacientes p ON c.ID_Paciente = p.ID_Paciente "
                     + "JOIN medicos m ON c.ID_Medico = m.ID_Medico "
                     + "JOIN especialidadesmedicas em ON c.ID_Especialidad = em.ID_Especialidad "
                     + "JOIN modalidadesconsulta mc ON c.ID_ModalidadConsulta = mc.ID_ModalidadConsulta "
                     + "JOIN sedes s ON c.ID_Sede = s.ID_Sede "
                     + "WHERE FechaCita=current_date()";
        
        model = new DefaultTableModel(null, Campos_tabla);
        
        try {
            
            Statement st = (Statement) conectar.createStatement();
            ResultSet rs = st.executeQuery(Query);

            while (rs.next()) {						
                informacion[0] = rs.getString("ID_Cita");
                informacion[1] = rs.getString("NombrePaciente");
                informacion[2] = rs.getString("NombreMedico");
                informacion[3] = rs.getString("Especialidad");
                informacion[4] = rs.getString("ModalidadConsulta");
                informacion[5] = rs.getString("FechaCita");
                informacion[6] = rs.getString("HoraCita");
                informacion[7] = rs.getString("Sede");
                model.addRow(informacion);
            }
            tabla_citas.setModel(model);
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }

    public Home() {
        initComponents();
        this.setLocationRelativeTo(null);
        mostrar_citashoy();

        Image icon = new ImageIcon(getClass().getResource("/images/icon.png")).getImage();
        setIconImage(icon);

        this.setTitle("Parcial - Bases de Datos Avanzadas");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_citas = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Home"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla_citas = new JTable()
        {
            public boolean isCellEditable(int row, int column)
            {
                for (int i = 0; i< tabla_citas.getRowCount();i++)
                {
                    if(row==i)
                    {
                        return false;
                    }
                }
                return true;
            }
        };
        tabla_citas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", ""
            }
        ));
        tabla_citas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_citasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabla_citas);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 730, 190));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 500));

        jButton8.setBackground(new java.awt.Color(255, 255, 0));
        jButton8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton8.setText("Examen Hoy");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, -1, -1));

        jButton7.setBackground(new java.awt.Color(0, 51, 255));
        jButton7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Todos mis examenes");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Buscar cita por cliente:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 170, 30));

        txt_search.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_searchKeyPressed(evt);
            }
        });
        jPanel1.add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 230, 30));

        jButton1.setBackground(new java.awt.Color(0, 102, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Buscar Paciente");
        jButton1.setToolTipText("Busca un paciente por su ID");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        jButton2.setBackground(new java.awt.Color(51, 204, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Agendar Cita");
        jButton2.setToolTipText("Agrega una cita al centro medico");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, -1));

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Reportes");
        jButton3.setToolTipText("Mira reportes dde valor para el centro medico");
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Buscar_paciente s = new Buscar_paciente();
        s.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Agendar_cita ac = new Agendar_cita();
        ac.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String Query = "select `c`.`ID_Cita` AS `ID_Cita`,`p`.`Nombres` AS `NombrePaciente`,`m`.`Nombre` AS `NombreMedico`,`em`.`NombreEspecialidad` AS `Especialidad`,`mc`.`NombreModalidad` AS `ModalidadConsulta`,`c`.`FechaCita` AS `FechaCita`,`c`.`HoraCita` AS `HoraCita`,`s`.`NombreSede` AS `Sede` from (((((`hospital`.`citas` `c` join `hospital`.`pacientes` `p` on(`c`.`ID_Paciente` = `p`.`ID_Paciente`)) join `hospital`.`medicos` `m` on(`c`.`ID_Medico` = `m`.`ID_Medico`)) join `hospital`.`especialidadesmedicas` `em` on(`c`.`ID_Especialidad` = `em`.`ID_Especialidad`)) join `hospital`.`modalidadesconsulta` `mc` on(`c`.`ID_ModalidadConsulta` = `mc`.`ID_ModalidadConsulta`)) join `hospital`.`sedes` `s` on(`c`.`ID_Sede` = `s`.`ID_Sede`))";
        
        model = new DefaultTableModel(null, Campos_tabla);
        
        try {
            Statement st = (Statement) conectar.createStatement();
            ResultSet rs = st.executeQuery(Query);

            while (rs.next()) {
                informacion[0] = rs.getString("ID_Cita");
                informacion[1] = rs.getString("NombrePaciente");
                informacion[2] = rs.getString("NombreMedico");
                informacion[3] = rs.getString("Especialidad");
                informacion[4] = rs.getString("ModalidadConsulta");
                informacion[5] = rs.getString("FechaCita");
                informacion[6] = rs.getString("HoraCita");
                informacion[7] = rs.getString("Sede");
                model.addRow(informacion);
            }
            tabla_citas.setModel(model);
        } catch (SQLException ex) {
            System.out.println(ex);
        }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        mostrar_citashoy();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void tabla_citasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_citasMouseClicked
        int columna = tabla_citas.getSelectedRow();
        if (evt.getClickCount() == 2) {

            Agendar_cita addc = new Agendar_cita();
            addc.setVisible(true);

            //Agendar_cita.txt_modalidad.setText(tabla_citas.getModel().getValueAt(columna, 0).toString());
            Agendar_cita.txt_client.setText(tabla_citas.getModel().getValueAt(columna, 1).toString());

//---------------------------------------------------------------------------
            ////importamos librerias para darle formato a nuestra fecha
            SimpleDateFormat formatoDelTexto = new SimpleDateFormat("yy-MM-dd");
            String fecha = tabla_citas.getModel().getValueAt(columna, 2).toString();
            Date dato = null;//date es un libreria
            try {
                dato = formatoDelTexto.parse(fecha);
            } catch (ParseException ex) {
                System.out.println(ex);
            }
            Agendar_cita.jc_date.setDate(dato);
//-------------------------------------------------------------------------------------------
            Agendar_cita.combo_hora.setSelectedItem(tabla_citas.getModel().getValueAt(columna, 3).toString());
            //Agendar_cita.combo_tipos.setSelectedItem(tabla_citas.getModel().getValueAt(columna, 4).toString());
            //Agendar_cita.combo_examen.setSelectedItem(tabla_citas.getModel().getValueAt(columna, 5).toString());

            Agendar_cita.btn_save.setEnabled(false);
            Agendar_cita.btn_update.setEnabled(true);
        }
    }//GEN-LAST:event_tabla_citasMouseClicked

    private void txt_searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyPressed
        
        String Query = "SELECT *FROM vista_citas WHERE NombrePaciente LIKE '%" + txt_search.getText() + "%' ";
        
        model = new DefaultTableModel(null, Campos_tabla);

        try {
            Statement st = (Statement) conectar.createStatement();
            ResultSet rs = st.executeQuery(Query);

            while (rs.next()) {
                informacion[0] = rs.getString("ID_Cita");
                informacion[1] = rs.getString("NombrePaciente");
                informacion[2] = rs.getString("NombreMedico");
                informacion[3] = rs.getString("Especialidad");
                informacion[4] = rs.getString("ModalidadConsulta");
                informacion[5] = rs.getString("FechaCita");
                informacion[6] = rs.getString("HoraCita");
                informacion[7] = rs.getString("Sede");
                model.addRow(informacion);
            }
            tabla_citas.setModel(model);
        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_txt_searchKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Reportes r = new Reportes();
        r.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Home().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tabla_citas;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
